//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace net.desktop.WebServicePostulacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", ConfigurationName="WebServicePostulacion.PostulacionWS")]
    public interface PostulacionWS {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/removePostulacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task removePostulacionAsync(net.desktop.WebServicePostulacion.removePostulacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findFullAllPostulacionRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findFullAllPostulacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findFullAllPostulacionResponse> findFullAllPostulacionAsync(net.desktop.WebServicePostulacion.findFullAllPostulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/cambiarEstadoPostulacionRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PostulacionWS/cambiarEstadoPostulacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.cambiarEstadoPostulacionResponse> cambiarEstadoPostulacionAsync(net.desktop.WebServicePostulacion.cambiarEstadoPostulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findFullPostulacionRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findFullPostulacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findFullPostulacionResponse> findFullPostulacionAsync(net.desktop.WebServicePostulacion.findFullPostulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findPostulacionFullPorRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findPostulacionFullPorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionFullPorResponse> findPostulacionFullPorAsync(net.desktop.WebServicePostulacion.findPostulacionFullPorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/createPostulacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task createPostulacionAsync(net.desktop.WebServicePostulacion.createPostulacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findPostulacionPorRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findPostulacionPorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionPorResponse> findPostulacionPorAsync(net.desktop.WebServicePostulacion.findPostulacionPorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findAllPostulacionRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findAllPostulacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findAllPostulacionResponse> findAllPostulacionAsync(net.desktop.WebServicePostulacion.findAllPostulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findPostulacionRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PostulacionWS/findPostulacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionResponse> findPostulacionAsync(net.desktop.WebServicePostulacion.findPostulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/PostulacionWS/editPostulacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task editPostulacionAsync(net.desktop.WebServicePostulacion.editPostulacion request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class removePostulacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity;
        
        public removePostulacion() {
        }
        
        public removePostulacion(int entity) {
            this.entity = entity;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/")]
    public partial class postulacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idAlumnoField;
        
        private int idCentroField;
        
        private int idEstadoField;
        
        private int idFamiliaField;
        
        private int idParticipacionField;
        
        private decimal idPostulacionField;
        
        private bool idPostulacionFieldSpecified;
        
        private int idProgramaField;
        
        private int idUsuarioField;
        
        private string nombreAlumnoField;
        
        private string nombreCentroField;
        
        private string nombreFamiliaField;
        
        private string nombreProgramaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAlumno {
            get {
                return this.idAlumnoField;
            }
            set {
                this.idAlumnoField = value;
                this.RaisePropertyChanged("idAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCentro {
            get {
                return this.idCentroField;
            }
            set {
                this.idCentroField = value;
                this.RaisePropertyChanged("idCentro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idFamilia {
            get {
                return this.idFamiliaField;
            }
            set {
                this.idFamiliaField = value;
                this.RaisePropertyChanged("idFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idParticipacion {
            get {
                return this.idParticipacionField;
            }
            set {
                this.idParticipacionField = value;
                this.RaisePropertyChanged("idParticipacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal idPostulacion {
            get {
                return this.idPostulacionField;
            }
            set {
                this.idPostulacionField = value;
                this.RaisePropertyChanged("idPostulacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPostulacionSpecified {
            get {
                return this.idPostulacionFieldSpecified;
            }
            set {
                this.idPostulacionFieldSpecified = value;
                this.RaisePropertyChanged("idPostulacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int idPrograma {
            get {
                return this.idProgramaField;
            }
            set {
                this.idProgramaField = value;
                this.RaisePropertyChanged("idPrograma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombreAlumno {
            get {
                return this.nombreAlumnoField;
            }
            set {
                this.nombreAlumnoField = value;
                this.RaisePropertyChanged("nombreAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string nombreCentro {
            get {
                return this.nombreCentroField;
            }
            set {
                this.nombreCentroField = value;
                this.RaisePropertyChanged("nombreCentro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string nombreFamilia {
            get {
                return this.nombreFamiliaField;
            }
            set {
                this.nombreFamiliaField = value;
                this.RaisePropertyChanged("nombreFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string nombrePrograma {
            get {
                return this.nombreProgramaField;
            }
            set {
                this.nombreProgramaField = value;
                this.RaisePropertyChanged("nombrePrograma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFullAllPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findFullAllPostulacionRequest {
        
        public findFullAllPostulacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFullAllPostulacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findFullAllPostulacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePostulacion.postulacion[] @return;
        
        public findFullAllPostulacionResponse() {
        }
        
        public findFullAllPostulacionResponse(net.desktop.WebServicePostulacion.postulacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambiarEstadoPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class cambiarEstadoPostulacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_postulacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        public cambiarEstadoPostulacionRequest() {
        }
        
        public cambiarEstadoPostulacionRequest(int id_postulacion, int id_estado) {
            this.id_postulacion = id_postulacion;
            this.id_estado = id_estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambiarEstadoPostulacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class cambiarEstadoPostulacionResponse {
        
        public cambiarEstadoPostulacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFullPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findFullPostulacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findFullPostulacionRequest() {
        }
        
        public findFullPostulacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFullPostulacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findFullPostulacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePostulacion.postulacion @return;
        
        public findFullPostulacionResponse() {
        }
        
        public findFullPostulacionResponse(net.desktop.WebServicePostulacion.postulacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPostulacionFullPor", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPostulacionFullPorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor;
        
        public findPostulacionFullPorRequest() {
        }
        
        public findPostulacionFullPorRequest(string campo, string valor) {
            this.campo = campo;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPostulacionFullPorResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPostulacionFullPorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePostulacion.postulacion[] @return;
        
        public findPostulacionFullPorResponse() {
        }
        
        public findPostulacionFullPorResponse(net.desktop.WebServicePostulacion.postulacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class createPostulacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_alumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_familia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_participacion;
        
        public createPostulacion() {
        }
        
        public createPostulacion(int id_alumno, int id_familia, int id_estado, int id_participacion) {
            this.id_alumno = id_alumno;
            this.id_familia = id_familia;
            this.id_estado = id_estado;
            this.id_participacion = id_participacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPostulacionPor", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPostulacionPorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor;
        
        public findPostulacionPorRequest() {
        }
        
        public findPostulacionPorRequest(string campo, string valor) {
            this.campo = campo;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPostulacionPorResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPostulacionPorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePostulacion.postulacion[] @return;
        
        public findPostulacionPorResponse() {
        }
        
        public findPostulacionPorResponse(net.desktop.WebServicePostulacion.postulacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllPostulacionRequest {
        
        public findAllPostulacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPostulacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllPostulacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePostulacion.postulacion[] @return;
        
        public findAllPostulacionResponse() {
        }
        
        public findAllPostulacionResponse(net.desktop.WebServicePostulacion.postulacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPostulacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findPostulacionRequest() {
        }
        
        public findPostulacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPostulacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPostulacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePostulacion.postulacion @return;
        
        public findPostulacionResponse() {
        }
        
        public findPostulacionResponse(net.desktop.WebServicePostulacion.postulacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class editPostulacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_postulacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_alumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_familia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_participacion;
        
        public editPostulacion() {
        }
        
        public editPostulacion(int id_postulacion, int id_alumno, int id_familia, int id_estado, int id_participacion) {
            this.id_postulacion = id_postulacion;
            this.id_alumno = id_alumno;
            this.id_familia = id_familia;
            this.id_estado = id_estado;
            this.id_participacion = id_participacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostulacionWSChannel : net.desktop.WebServicePostulacion.PostulacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostulacionWSClient : System.ServiceModel.ClientBase<net.desktop.WebServicePostulacion.PostulacionWS>, net.desktop.WebServicePostulacion.PostulacionWS {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PostulacionWSClient() : 
                base(PostulacionWSClient.GetDefaultBinding(), PostulacionWSClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.PostulacionWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostulacionWSClient(EndpointConfiguration endpointConfiguration) : 
                base(PostulacionWSClient.GetBindingForEndpoint(endpointConfiguration), PostulacionWSClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostulacionWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PostulacionWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostulacionWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PostulacionWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostulacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServicePostulacion.PostulacionWS.removePostulacionAsync(net.desktop.WebServicePostulacion.removePostulacion request) {
            return base.Channel.removePostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task removePostulacionAsync(int entity) {
            net.desktop.WebServicePostulacion.removePostulacion inValue = new net.desktop.WebServicePostulacion.removePostulacion();
            inValue.entity = entity;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).removePostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findFullAllPostulacionResponse> net.desktop.WebServicePostulacion.PostulacionWS.findFullAllPostulacionAsync(net.desktop.WebServicePostulacion.findFullAllPostulacionRequest request) {
            return base.Channel.findFullAllPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findFullAllPostulacionResponse> findFullAllPostulacionAsync() {
            net.desktop.WebServicePostulacion.findFullAllPostulacionRequest inValue = new net.desktop.WebServicePostulacion.findFullAllPostulacionRequest();
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).findFullAllPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.cambiarEstadoPostulacionResponse> net.desktop.WebServicePostulacion.PostulacionWS.cambiarEstadoPostulacionAsync(net.desktop.WebServicePostulacion.cambiarEstadoPostulacionRequest request) {
            return base.Channel.cambiarEstadoPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.cambiarEstadoPostulacionResponse> cambiarEstadoPostulacionAsync(int id_postulacion, int id_estado) {
            net.desktop.WebServicePostulacion.cambiarEstadoPostulacionRequest inValue = new net.desktop.WebServicePostulacion.cambiarEstadoPostulacionRequest();
            inValue.id_postulacion = id_postulacion;
            inValue.id_estado = id_estado;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).cambiarEstadoPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findFullPostulacionResponse> net.desktop.WebServicePostulacion.PostulacionWS.findFullPostulacionAsync(net.desktop.WebServicePostulacion.findFullPostulacionRequest request) {
            return base.Channel.findFullPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findFullPostulacionResponse> findFullPostulacionAsync(int id) {
            net.desktop.WebServicePostulacion.findFullPostulacionRequest inValue = new net.desktop.WebServicePostulacion.findFullPostulacionRequest();
            inValue.id = id;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).findFullPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionFullPorResponse> net.desktop.WebServicePostulacion.PostulacionWS.findPostulacionFullPorAsync(net.desktop.WebServicePostulacion.findPostulacionFullPorRequest request) {
            return base.Channel.findPostulacionFullPorAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionFullPorResponse> findPostulacionFullPorAsync(string campo, string valor) {
            net.desktop.WebServicePostulacion.findPostulacionFullPorRequest inValue = new net.desktop.WebServicePostulacion.findPostulacionFullPorRequest();
            inValue.campo = campo;
            inValue.valor = valor;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).findPostulacionFullPorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServicePostulacion.PostulacionWS.createPostulacionAsync(net.desktop.WebServicePostulacion.createPostulacion request) {
            return base.Channel.createPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task createPostulacionAsync(int id_alumno, int id_familia, int id_estado, int id_participacion) {
            net.desktop.WebServicePostulacion.createPostulacion inValue = new net.desktop.WebServicePostulacion.createPostulacion();
            inValue.id_alumno = id_alumno;
            inValue.id_familia = id_familia;
            inValue.id_estado = id_estado;
            inValue.id_participacion = id_participacion;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).createPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionPorResponse> net.desktop.WebServicePostulacion.PostulacionWS.findPostulacionPorAsync(net.desktop.WebServicePostulacion.findPostulacionPorRequest request) {
            return base.Channel.findPostulacionPorAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionPorResponse> findPostulacionPorAsync(string campo, string valor) {
            net.desktop.WebServicePostulacion.findPostulacionPorRequest inValue = new net.desktop.WebServicePostulacion.findPostulacionPorRequest();
            inValue.campo = campo;
            inValue.valor = valor;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).findPostulacionPorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findAllPostulacionResponse> net.desktop.WebServicePostulacion.PostulacionWS.findAllPostulacionAsync(net.desktop.WebServicePostulacion.findAllPostulacionRequest request) {
            return base.Channel.findAllPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findAllPostulacionResponse> findAllPostulacionAsync() {
            net.desktop.WebServicePostulacion.findAllPostulacionRequest inValue = new net.desktop.WebServicePostulacion.findAllPostulacionRequest();
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).findAllPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionResponse> net.desktop.WebServicePostulacion.PostulacionWS.findPostulacionAsync(net.desktop.WebServicePostulacion.findPostulacionRequest request) {
            return base.Channel.findPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePostulacion.findPostulacionResponse> findPostulacionAsync(int id) {
            net.desktop.WebServicePostulacion.findPostulacionRequest inValue = new net.desktop.WebServicePostulacion.findPostulacionRequest();
            inValue.id = id;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).findPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServicePostulacion.PostulacionWS.editPostulacionAsync(net.desktop.WebServicePostulacion.editPostulacion request) {
            return base.Channel.editPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task editPostulacionAsync(int id_postulacion, int id_alumno, int id_familia, int id_estado, int id_participacion) {
            net.desktop.WebServicePostulacion.editPostulacion inValue = new net.desktop.WebServicePostulacion.editPostulacion();
            inValue.id_postulacion = id_postulacion;
            inValue.id_alumno = id_alumno;
            inValue.id_familia = id_familia;
            inValue.id_estado = id_estado;
            inValue.id_participacion = id_participacion;
            return ((net.desktop.WebServicePostulacion.PostulacionWS)(this)).editPostulacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PostulacionWSPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PostulacionWSPort)) {
                return new System.ServiceModel.EndpointAddress("http://ws.huevoscopita.cl/webservice/PostulacionWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PostulacionWSClient.GetBindingForEndpoint(EndpointConfiguration.PostulacionWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PostulacionWSClient.GetEndpointAddress(EndpointConfiguration.PostulacionWSPort);
        }
        
        public enum EndpointConfiguration {
            
            PostulacionWSPort,
        }
    }
}
