//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace net.desktop.WebServiceEstadoPostulacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", ConfigurationName="WebServiceEstadoPostulacion.EstadoPostulacionWS")]
    public interface EstadoPostulacionWS {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/createEstadoPostulacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task createEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.createEstadoPostulacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/findEstadoPostulacionRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/findEstadoPostulacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionResponse> findEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/editEstadoPostulacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task editEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.editEstadoPostulacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/findEstadoPostulacionPorRequest" +
            "", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/findEstadoPostulacionPorRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionPorResponse> findEstadoPostulacionPorAsync(net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionPorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/removeEstadoPostulacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task removeEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.removeEstadoPostulacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/findAllEstadoPostulacionRequest" +
            "", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoPostulacionWS/findAllEstadoPostulacionRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findAllEstadoPostulacionResponse> findAllEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.findAllEstadoPostulacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createEstadoPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class createEstadoPostulacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public createEstadoPostulacion() {
        }
        
        public createEstadoPostulacion(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/")]
    public partial class estadoPostulacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoPostulacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findEstadoPostulacionRequest() {
        }
        
        public findEstadoPostulacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoPostulacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoPostulacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoPostulacion.estadoPostulacion @return;
        
        public findEstadoPostulacionResponse() {
        }
        
        public findEstadoPostulacionResponse(net.desktop.WebServiceEstadoPostulacion.estadoPostulacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEstadoPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class editEstadoPostulacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public editEstadoPostulacion() {
        }
        
        public editEstadoPostulacion(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoPostulacionPor", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoPostulacionPorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor;
        
        public findEstadoPostulacionPorRequest() {
        }
        
        public findEstadoPostulacionPorRequest(string campo, string valor) {
            this.campo = campo;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoPostulacionPorResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoPostulacionPorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoPostulacion.estadoPostulacion[] @return;
        
        public findEstadoPostulacionPorResponse() {
        }
        
        public findEstadoPostulacionPorResponse(net.desktop.WebServiceEstadoPostulacion.estadoPostulacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeEstadoPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class removeEstadoPostulacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity;
        
        public removeEstadoPostulacion() {
        }
        
        public removeEstadoPostulacion(int entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoPostulacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoPostulacionRequest {
        
        public findAllEstadoPostulacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoPostulacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoPostulacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoPostulacion.estadoPostulacion[] @return;
        
        public findAllEstadoPostulacionResponse() {
        }
        
        public findAllEstadoPostulacionResponse(net.desktop.WebServiceEstadoPostulacion.estadoPostulacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadoPostulacionWSChannel : net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoPostulacionWSClient : System.ServiceModel.ClientBase<net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS>, net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EstadoPostulacionWSClient() : 
                base(EstadoPostulacionWSClient.GetDefaultBinding(), EstadoPostulacionWSClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.EstadoPostulacionWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoPostulacionWSClient(EndpointConfiguration endpointConfiguration) : 
                base(EstadoPostulacionWSClient.GetBindingForEndpoint(endpointConfiguration), EstadoPostulacionWSClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoPostulacionWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EstadoPostulacionWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoPostulacionWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EstadoPostulacionWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoPostulacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS.createEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.createEstadoPostulacion request) {
            return base.Channel.createEstadoPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task createEstadoPostulacionAsync(int id_estado, string estado) {
            net.desktop.WebServiceEstadoPostulacion.createEstadoPostulacion inValue = new net.desktop.WebServiceEstadoPostulacion.createEstadoPostulacion();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS)(this)).createEstadoPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionResponse> net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS.findEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionRequest request) {
            return base.Channel.findEstadoPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionResponse> findEstadoPostulacionAsync(int id) {
            net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionRequest inValue = new net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionRequest();
            inValue.id = id;
            return ((net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS)(this)).findEstadoPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS.editEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.editEstadoPostulacion request) {
            return base.Channel.editEstadoPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task editEstadoPostulacionAsync(int id_estado, string estado) {
            net.desktop.WebServiceEstadoPostulacion.editEstadoPostulacion inValue = new net.desktop.WebServiceEstadoPostulacion.editEstadoPostulacion();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS)(this)).editEstadoPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionPorResponse> net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS.findEstadoPostulacionPorAsync(net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionPorRequest request) {
            return base.Channel.findEstadoPostulacionPorAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionPorResponse> findEstadoPostulacionPorAsync(string campo, string valor) {
            net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionPorRequest inValue = new net.desktop.WebServiceEstadoPostulacion.findEstadoPostulacionPorRequest();
            inValue.campo = campo;
            inValue.valor = valor;
            return ((net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS)(this)).findEstadoPostulacionPorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS.removeEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.removeEstadoPostulacion request) {
            return base.Channel.removeEstadoPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task removeEstadoPostulacionAsync(int entity) {
            net.desktop.WebServiceEstadoPostulacion.removeEstadoPostulacion inValue = new net.desktop.WebServiceEstadoPostulacion.removeEstadoPostulacion();
            inValue.entity = entity;
            return ((net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS)(this)).removeEstadoPostulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findAllEstadoPostulacionResponse> net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS.findAllEstadoPostulacionAsync(net.desktop.WebServiceEstadoPostulacion.findAllEstadoPostulacionRequest request) {
            return base.Channel.findAllEstadoPostulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPostulacion.findAllEstadoPostulacionResponse> findAllEstadoPostulacionAsync() {
            net.desktop.WebServiceEstadoPostulacion.findAllEstadoPostulacionRequest inValue = new net.desktop.WebServiceEstadoPostulacion.findAllEstadoPostulacionRequest();
            return ((net.desktop.WebServiceEstadoPostulacion.EstadoPostulacionWS)(this)).findAllEstadoPostulacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoPostulacionWSPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoPostulacionWSPort)) {
                return new System.ServiceModel.EndpointAddress("http://ws.huevoscopita.cl/webservice/EstadoPostulacionWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return EstadoPostulacionWSClient.GetBindingForEndpoint(EndpointConfiguration.EstadoPostulacionWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return EstadoPostulacionWSClient.GetEndpointAddress(EndpointConfiguration.EstadoPostulacionWSPort);
        }
        
        public enum EndpointConfiguration {
            
            EstadoPostulacionWSPort,
        }
    }
}
