//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace net.desktop.WebServiceEsadoFamilia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", ConfigurationName="WebServiceEsadoFamilia.EstadoFamiliaWS")]
    public interface EstadoFamiliaWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/findEstadoFamiliaRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/findEstadoFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaResponse> findEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/removeEstadoFamilia")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task removeEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.removeEstadoFamilia request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/editEstadoFamilia")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task editEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.editEstadoFamilia request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/findEstadoFamiliaPorRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/findEstadoFamiliaPorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaPorResponse> findEstadoFamiliaPorAsync(net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaPorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/createEstadoFamilia")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task createEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.createEstadoFamilia request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/findAllEstadoFamiliaRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoFamiliaWS/findAllEstadoFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findAllEstadoFamiliaResponse> findAllEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.findAllEstadoFamiliaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/")]
    public partial class estadoFamilia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoFamilia", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoFamiliaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findEstadoFamiliaRequest() {
        }
        
        public findEstadoFamiliaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoFamiliaResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEsadoFamilia.estadoFamilia @return;
        
        public findEstadoFamiliaResponse() {
        }
        
        public findEstadoFamiliaResponse(net.desktop.WebServiceEsadoFamilia.estadoFamilia @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeEstadoFamilia", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class removeEstadoFamilia {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity;
        
        public removeEstadoFamilia() {
        }
        
        public removeEstadoFamilia(int entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEstadoFamilia", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class editEstadoFamilia {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public editEstadoFamilia() {
        }
        
        public editEstadoFamilia(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoFamiliaPor", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoFamiliaPorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor;
        
        public findEstadoFamiliaPorRequest() {
        }
        
        public findEstadoFamiliaPorRequest(string campo, string valor) {
            this.campo = campo;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoFamiliaPorResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoFamiliaPorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEsadoFamilia.estadoFamilia[] @return;
        
        public findEstadoFamiliaPorResponse() {
        }
        
        public findEstadoFamiliaPorResponse(net.desktop.WebServiceEsadoFamilia.estadoFamilia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createEstadoFamilia", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class createEstadoFamilia {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public createEstadoFamilia() {
        }
        
        public createEstadoFamilia(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoFamilia", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoFamiliaRequest {
        
        public findAllEstadoFamiliaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoFamiliaResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEsadoFamilia.estadoFamilia[] @return;
        
        public findAllEstadoFamiliaResponse() {
        }
        
        public findAllEstadoFamiliaResponse(net.desktop.WebServiceEsadoFamilia.estadoFamilia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadoFamiliaWSChannel : net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoFamiliaWSClient : System.ServiceModel.ClientBase<net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS>, net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EstadoFamiliaWSClient() : 
                base(EstadoFamiliaWSClient.GetDefaultBinding(), EstadoFamiliaWSClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.EstadoFamiliaWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoFamiliaWSClient(EndpointConfiguration endpointConfiguration) : 
                base(EstadoFamiliaWSClient.GetBindingForEndpoint(endpointConfiguration), EstadoFamiliaWSClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoFamiliaWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EstadoFamiliaWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoFamiliaWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EstadoFamiliaWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoFamiliaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaResponse> net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS.findEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaRequest request) {
            return base.Channel.findEstadoFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaResponse> findEstadoFamiliaAsync(int id) {
            net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaRequest inValue = new net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaRequest();
            inValue.id = id;
            return ((net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS)(this)).findEstadoFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS.removeEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.removeEstadoFamilia request) {
            return base.Channel.removeEstadoFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task removeEstadoFamiliaAsync(int entity) {
            net.desktop.WebServiceEsadoFamilia.removeEstadoFamilia inValue = new net.desktop.WebServiceEsadoFamilia.removeEstadoFamilia();
            inValue.entity = entity;
            return ((net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS)(this)).removeEstadoFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS.editEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.editEstadoFamilia request) {
            return base.Channel.editEstadoFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task editEstadoFamiliaAsync(int id_estado, string estado) {
            net.desktop.WebServiceEsadoFamilia.editEstadoFamilia inValue = new net.desktop.WebServiceEsadoFamilia.editEstadoFamilia();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS)(this)).editEstadoFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaPorResponse> net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS.findEstadoFamiliaPorAsync(net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaPorRequest request) {
            return base.Channel.findEstadoFamiliaPorAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaPorResponse> findEstadoFamiliaPorAsync(string campo, string valor) {
            net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaPorRequest inValue = new net.desktop.WebServiceEsadoFamilia.findEstadoFamiliaPorRequest();
            inValue.campo = campo;
            inValue.valor = valor;
            return ((net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS)(this)).findEstadoFamiliaPorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS.createEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.createEstadoFamilia request) {
            return base.Channel.createEstadoFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task createEstadoFamiliaAsync(int id_estado, string estado) {
            net.desktop.WebServiceEsadoFamilia.createEstadoFamilia inValue = new net.desktop.WebServiceEsadoFamilia.createEstadoFamilia();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS)(this)).createEstadoFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findAllEstadoFamiliaResponse> net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS.findAllEstadoFamiliaAsync(net.desktop.WebServiceEsadoFamilia.findAllEstadoFamiliaRequest request) {
            return base.Channel.findAllEstadoFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEsadoFamilia.findAllEstadoFamiliaResponse> findAllEstadoFamiliaAsync() {
            net.desktop.WebServiceEsadoFamilia.findAllEstadoFamiliaRequest inValue = new net.desktop.WebServiceEsadoFamilia.findAllEstadoFamiliaRequest();
            return ((net.desktop.WebServiceEsadoFamilia.EstadoFamiliaWS)(this)).findAllEstadoFamiliaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoFamiliaWSPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoFamiliaWSPort)) {
                return new System.ServiceModel.EndpointAddress("http://ws.huevoscopita.cl/webservice/EstadoFamiliaWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return EstadoFamiliaWSClient.GetBindingForEndpoint(EndpointConfiguration.EstadoFamiliaWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return EstadoFamiliaWSClient.GetEndpointAddress(EndpointConfiguration.EstadoFamiliaWSPort);
        }
        
        public enum EndpointConfiguration {
            
            EstadoFamiliaWSPort,
        }
    }
}
