//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace net.desktop.WebServiceEstadoParticipacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", ConfigurationName="WebServiceEstadoParticipacion.EstadoParticipacionWS")]
    public interface EstadoParticipacionWS {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/editEstadoParticipacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task editEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.editEstadoParticipacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/findEstadoParticipacionPorReq" +
            "uest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/findEstadoParticipacionPorRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionPorResponse> findEstadoParticipacionPorAsync(net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionPorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/removeEstadoParticipacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task removeEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.removeEstadoParticipacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/findEstadoParticipacionReques" +
            "t", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/findEstadoParticipacionRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionResponse> findEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/createEstadoParticipacion")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task createEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.createEstadoParticipacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/findAllEstadoParticipacionReq" +
            "uest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoParticipacionWS/findAllEstadoParticipacionRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findAllEstadoParticipacionResponse> findAllEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.findAllEstadoParticipacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEstadoParticipacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class editEstadoParticipacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public editEstadoParticipacion() {
        }
        
        public editEstadoParticipacion(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/")]
    public partial class estadoParticipacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoParticipacionPor", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoParticipacionPorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor;
        
        public findEstadoParticipacionPorRequest() {
        }
        
        public findEstadoParticipacionPorRequest(string campo, string valor) {
            this.campo = campo;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoParticipacionPorResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoParticipacionPorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoParticipacion.estadoParticipacion[] @return;
        
        public findEstadoParticipacionPorResponse() {
        }
        
        public findEstadoParticipacionPorResponse(net.desktop.WebServiceEstadoParticipacion.estadoParticipacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeEstadoParticipacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class removeEstadoParticipacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity;
        
        public removeEstadoParticipacion() {
        }
        
        public removeEstadoParticipacion(int entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoParticipacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoParticipacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findEstadoParticipacionRequest() {
        }
        
        public findEstadoParticipacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoParticipacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoParticipacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoParticipacion.estadoParticipacion @return;
        
        public findEstadoParticipacionResponse() {
        }
        
        public findEstadoParticipacionResponse(net.desktop.WebServiceEstadoParticipacion.estadoParticipacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createEstadoParticipacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class createEstadoParticipacion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public createEstadoParticipacion() {
        }
        
        public createEstadoParticipacion(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoParticipacion", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoParticipacionRequest {
        
        public findAllEstadoParticipacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoParticipacionResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoParticipacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoParticipacion.estadoParticipacion[] @return;
        
        public findAllEstadoParticipacionResponse() {
        }
        
        public findAllEstadoParticipacionResponse(net.desktop.WebServiceEstadoParticipacion.estadoParticipacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadoParticipacionWSChannel : net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoParticipacionWSClient : System.ServiceModel.ClientBase<net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS>, net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EstadoParticipacionWSClient() : 
                base(EstadoParticipacionWSClient.GetDefaultBinding(), EstadoParticipacionWSClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.EstadoParticipacionWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoParticipacionWSClient(EndpointConfiguration endpointConfiguration) : 
                base(EstadoParticipacionWSClient.GetBindingForEndpoint(endpointConfiguration), EstadoParticipacionWSClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoParticipacionWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EstadoParticipacionWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoParticipacionWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EstadoParticipacionWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoParticipacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS.editEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.editEstadoParticipacion request) {
            return base.Channel.editEstadoParticipacionAsync(request);
        }
        
        public System.Threading.Tasks.Task editEstadoParticipacionAsync(int id_estado, string estado) {
            net.desktop.WebServiceEstadoParticipacion.editEstadoParticipacion inValue = new net.desktop.WebServiceEstadoParticipacion.editEstadoParticipacion();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS)(this)).editEstadoParticipacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionPorResponse> net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS.findEstadoParticipacionPorAsync(net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionPorRequest request) {
            return base.Channel.findEstadoParticipacionPorAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionPorResponse> findEstadoParticipacionPorAsync(string campo, string valor) {
            net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionPorRequest inValue = new net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionPorRequest();
            inValue.campo = campo;
            inValue.valor = valor;
            return ((net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS)(this)).findEstadoParticipacionPorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS.removeEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.removeEstadoParticipacion request) {
            return base.Channel.removeEstadoParticipacionAsync(request);
        }
        
        public System.Threading.Tasks.Task removeEstadoParticipacionAsync(int entity) {
            net.desktop.WebServiceEstadoParticipacion.removeEstadoParticipacion inValue = new net.desktop.WebServiceEstadoParticipacion.removeEstadoParticipacion();
            inValue.entity = entity;
            return ((net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS)(this)).removeEstadoParticipacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionResponse> net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS.findEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionRequest request) {
            return base.Channel.findEstadoParticipacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionResponse> findEstadoParticipacionAsync(int id) {
            net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionRequest inValue = new net.desktop.WebServiceEstadoParticipacion.findEstadoParticipacionRequest();
            inValue.id = id;
            return ((net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS)(this)).findEstadoParticipacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS.createEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.createEstadoParticipacion request) {
            return base.Channel.createEstadoParticipacionAsync(request);
        }
        
        public System.Threading.Tasks.Task createEstadoParticipacionAsync(int id_estado, string estado) {
            net.desktop.WebServiceEstadoParticipacion.createEstadoParticipacion inValue = new net.desktop.WebServiceEstadoParticipacion.createEstadoParticipacion();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS)(this)).createEstadoParticipacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findAllEstadoParticipacionResponse> net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS.findAllEstadoParticipacionAsync(net.desktop.WebServiceEstadoParticipacion.findAllEstadoParticipacionRequest request) {
            return base.Channel.findAllEstadoParticipacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoParticipacion.findAllEstadoParticipacionResponse> findAllEstadoParticipacionAsync() {
            net.desktop.WebServiceEstadoParticipacion.findAllEstadoParticipacionRequest inValue = new net.desktop.WebServiceEstadoParticipacion.findAllEstadoParticipacionRequest();
            return ((net.desktop.WebServiceEstadoParticipacion.EstadoParticipacionWS)(this)).findAllEstadoParticipacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoParticipacionWSPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoParticipacionWSPort)) {
                return new System.ServiceModel.EndpointAddress("http://ws.huevoscopita.cl/webservice/EstadoParticipacionWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return EstadoParticipacionWSClient.GetBindingForEndpoint(EndpointConfiguration.EstadoParticipacionWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return EstadoParticipacionWSClient.GetEndpointAddress(EndpointConfiguration.EstadoParticipacionWSPort);
        }
        
        public enum EndpointConfiguration {
            
            EstadoParticipacionWSPort,
        }
    }
}
