//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace net.desktop.WebServicePerfil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", ConfigurationName="WebServicePerfil.PerfilUsuarioWS")]
    public interface PerfilUsuarioWS {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/editPerfilUsuario")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task editPerfilUsuarioAsync(net.desktop.WebServicePerfil.editPerfilUsuario request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/removePerfilUsuario")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task removePerfilUsuarioAsync(net.desktop.WebServicePerfil.removePerfilUsuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/findAllPerfilUsuarioRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/findAllPerfilUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findAllPerfilUsuarioResponse> findAllPerfilUsuarioAsync(net.desktop.WebServicePerfil.findAllPerfilUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/findPerfilUsuarioPorRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/findPerfilUsuarioPorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findPerfilUsuarioPorResponse> findPerfilUsuarioPorAsync(net.desktop.WebServicePerfil.findPerfilUsuarioPorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/findPerfilUsuarioRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/findPerfilUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findPerfilUsuarioResponse> findPerfilUsuarioAsync(net.desktop.WebServicePerfil.findPerfilUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/PerfilUsuarioWS/createPerfilUsuario")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task createPerfilUsuarioAsync(net.desktop.WebServicePerfil.createPerfilUsuario request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPerfilUsuario", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class editPerfilUsuario {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_perfil_usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_perfil;
        
        public editPerfilUsuario() {
        }
        
        public editPerfilUsuario(int id_perfil_usuario, string nombre_perfil) {
            this.id_perfil_usuario = id_perfil_usuario;
            this.nombre_perfil = nombre_perfil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePerfilUsuario", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class removePerfilUsuario {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity;
        
        public removePerfilUsuario() {
        }
        
        public removePerfilUsuario(int entity) {
            this.entity = entity;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/")]
    public partial class perfilUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idPerfilUsuarioField;
        
        private bool idPerfilUsuarioFieldSpecified;
        
        private string nombrePerfilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal idPerfilUsuario {
            get {
                return this.idPerfilUsuarioField;
            }
            set {
                this.idPerfilUsuarioField = value;
                this.RaisePropertyChanged("idPerfilUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPerfilUsuarioSpecified {
            get {
                return this.idPerfilUsuarioFieldSpecified;
            }
            set {
                this.idPerfilUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idPerfilUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombrePerfil {
            get {
                return this.nombrePerfilField;
            }
            set {
                this.nombrePerfilField = value;
                this.RaisePropertyChanged("nombrePerfil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPerfilUsuario", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllPerfilUsuarioRequest {
        
        public findAllPerfilUsuarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPerfilUsuarioResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllPerfilUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePerfil.perfilUsuario[] @return;
        
        public findAllPerfilUsuarioResponse() {
        }
        
        public findAllPerfilUsuarioResponse(net.desktop.WebServicePerfil.perfilUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPerfilUsuarioPor", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPerfilUsuarioPorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor;
        
        public findPerfilUsuarioPorRequest() {
        }
        
        public findPerfilUsuarioPorRequest(string campo, string valor) {
            this.campo = campo;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPerfilUsuarioPorResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPerfilUsuarioPorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePerfil.perfilUsuario[] @return;
        
        public findPerfilUsuarioPorResponse() {
        }
        
        public findPerfilUsuarioPorResponse(net.desktop.WebServicePerfil.perfilUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPerfilUsuario", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPerfilUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findPerfilUsuarioRequest() {
        }
        
        public findPerfilUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPerfilUsuarioResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findPerfilUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServicePerfil.perfilUsuario @return;
        
        public findPerfilUsuarioResponse() {
        }
        
        public findPerfilUsuarioResponse(net.desktop.WebServicePerfil.perfilUsuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createPerfilUsuario", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class createPerfilUsuario {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_perfil_usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_perfil;
        
        public createPerfilUsuario() {
        }
        
        public createPerfilUsuario(int id_perfil_usuario, string nombre_perfil) {
            this.id_perfil_usuario = id_perfil_usuario;
            this.nombre_perfil = nombre_perfil;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PerfilUsuarioWSChannel : net.desktop.WebServicePerfil.PerfilUsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerfilUsuarioWSClient : System.ServiceModel.ClientBase<net.desktop.WebServicePerfil.PerfilUsuarioWS>, net.desktop.WebServicePerfil.PerfilUsuarioWS {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PerfilUsuarioWSClient() : 
                base(PerfilUsuarioWSClient.GetDefaultBinding(), PerfilUsuarioWSClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.PerfilUsuarioWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PerfilUsuarioWSClient(EndpointConfiguration endpointConfiguration) : 
                base(PerfilUsuarioWSClient.GetBindingForEndpoint(endpointConfiguration), PerfilUsuarioWSClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PerfilUsuarioWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PerfilUsuarioWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PerfilUsuarioWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PerfilUsuarioWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PerfilUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServicePerfil.PerfilUsuarioWS.editPerfilUsuarioAsync(net.desktop.WebServicePerfil.editPerfilUsuario request) {
            return base.Channel.editPerfilUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task editPerfilUsuarioAsync(int id_perfil_usuario, string nombre_perfil) {
            net.desktop.WebServicePerfil.editPerfilUsuario inValue = new net.desktop.WebServicePerfil.editPerfilUsuario();
            inValue.id_perfil_usuario = id_perfil_usuario;
            inValue.nombre_perfil = nombre_perfil;
            return ((net.desktop.WebServicePerfil.PerfilUsuarioWS)(this)).editPerfilUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServicePerfil.PerfilUsuarioWS.removePerfilUsuarioAsync(net.desktop.WebServicePerfil.removePerfilUsuario request) {
            return base.Channel.removePerfilUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task removePerfilUsuarioAsync(int entity) {
            net.desktop.WebServicePerfil.removePerfilUsuario inValue = new net.desktop.WebServicePerfil.removePerfilUsuario();
            inValue.entity = entity;
            return ((net.desktop.WebServicePerfil.PerfilUsuarioWS)(this)).removePerfilUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findAllPerfilUsuarioResponse> net.desktop.WebServicePerfil.PerfilUsuarioWS.findAllPerfilUsuarioAsync(net.desktop.WebServicePerfil.findAllPerfilUsuarioRequest request) {
            return base.Channel.findAllPerfilUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findAllPerfilUsuarioResponse> findAllPerfilUsuarioAsync() {
            net.desktop.WebServicePerfil.findAllPerfilUsuarioRequest inValue = new net.desktop.WebServicePerfil.findAllPerfilUsuarioRequest();
            return ((net.desktop.WebServicePerfil.PerfilUsuarioWS)(this)).findAllPerfilUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findPerfilUsuarioPorResponse> net.desktop.WebServicePerfil.PerfilUsuarioWS.findPerfilUsuarioPorAsync(net.desktop.WebServicePerfil.findPerfilUsuarioPorRequest request) {
            return base.Channel.findPerfilUsuarioPorAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findPerfilUsuarioPorResponse> findPerfilUsuarioPorAsync(string campo, string valor) {
            net.desktop.WebServicePerfil.findPerfilUsuarioPorRequest inValue = new net.desktop.WebServicePerfil.findPerfilUsuarioPorRequest();
            inValue.campo = campo;
            inValue.valor = valor;
            return ((net.desktop.WebServicePerfil.PerfilUsuarioWS)(this)).findPerfilUsuarioPorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findPerfilUsuarioResponse> net.desktop.WebServicePerfil.PerfilUsuarioWS.findPerfilUsuarioAsync(net.desktop.WebServicePerfil.findPerfilUsuarioRequest request) {
            return base.Channel.findPerfilUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServicePerfil.findPerfilUsuarioResponse> findPerfilUsuarioAsync(int id) {
            net.desktop.WebServicePerfil.findPerfilUsuarioRequest inValue = new net.desktop.WebServicePerfil.findPerfilUsuarioRequest();
            inValue.id = id;
            return ((net.desktop.WebServicePerfil.PerfilUsuarioWS)(this)).findPerfilUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServicePerfil.PerfilUsuarioWS.createPerfilUsuarioAsync(net.desktop.WebServicePerfil.createPerfilUsuario request) {
            return base.Channel.createPerfilUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task createPerfilUsuarioAsync(int id_perfil_usuario, string nombre_perfil) {
            net.desktop.WebServicePerfil.createPerfilUsuario inValue = new net.desktop.WebServicePerfil.createPerfilUsuario();
            inValue.id_perfil_usuario = id_perfil_usuario;
            inValue.nombre_perfil = nombre_perfil;
            return ((net.desktop.WebServicePerfil.PerfilUsuarioWS)(this)).createPerfilUsuarioAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PerfilUsuarioWSPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PerfilUsuarioWSPort)) {
                return new System.ServiceModel.EndpointAddress("http://ws.huevoscopita.cl/webservice/PerfilUsuarioWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PerfilUsuarioWSClient.GetBindingForEndpoint(EndpointConfiguration.PerfilUsuarioWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PerfilUsuarioWSClient.GetEndpointAddress(EndpointConfiguration.PerfilUsuarioWSPort);
        }
        
        public enum EndpointConfiguration {
            
            PerfilUsuarioWSPort,
        }
    }
}
