//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace net.desktop.WebServiceEstadoPrograma {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", ConfigurationName="WebServiceEstadoPrograma.EstadoProgramaWS")]
    public interface EstadoProgramaWS {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/editEstadoPrograma")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task editEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.editEstadoPrograma request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/removeEstadoPrograma")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task removeEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.removeEstadoPrograma request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/createEstadoPrograma")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task createEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.createEstadoPrograma request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/findAllEstadoProgramaRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/findAllEstadoProgramaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findAllEstadoProgramaResponse> findAllEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.findAllEstadoProgramaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/findEstadoProgramaPorRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/findEstadoProgramaPorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findEstadoProgramaPorResponse> findEstadoProgramaPorAsync(net.desktop.WebServiceEstadoPrograma.findEstadoProgramaPorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/findEstadoProgramaRequest", ReplyAction="http://ws.cem.pft8461.duoc.cl/EstadoProgramaWS/findEstadoProgramaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findEstadoProgramaResponse> findEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.findEstadoProgramaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEstadoPrograma", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class editEstadoPrograma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public editEstadoPrograma() {
        }
        
        public editEstadoPrograma(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeEstadoPrograma", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class removeEstadoPrograma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entity;
        
        public removeEstadoPrograma() {
        }
        
        public removeEstadoPrograma(int entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createEstadoPrograma", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class createEstadoPrograma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public createEstadoPrograma() {
        }
        
        public createEstadoPrograma(int id_estado, string estado) {
            this.id_estado = id_estado;
            this.estado = estado;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/")]
    public partial class estadoPrograma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private decimal idEstadoField;
        
        private bool idEstadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoSpecified {
            get {
                return this.idEstadoFieldSpecified;
            }
            set {
                this.idEstadoFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoPrograma", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoProgramaRequest {
        
        public findAllEstadoProgramaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllEstadoProgramaResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findAllEstadoProgramaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoPrograma.estadoPrograma[] @return;
        
        public findAllEstadoProgramaResponse() {
        }
        
        public findAllEstadoProgramaResponse(net.desktop.WebServiceEstadoPrograma.estadoPrograma[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoProgramaPor", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoProgramaPorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor;
        
        public findEstadoProgramaPorRequest() {
        }
        
        public findEstadoProgramaPorRequest(string campo, string valor) {
            this.campo = campo;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoProgramaPorResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoProgramaPorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoPrograma.estadoPrograma[] @return;
        
        public findEstadoProgramaPorResponse() {
        }
        
        public findEstadoProgramaPorResponse(net.desktop.WebServiceEstadoPrograma.estadoPrograma[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoPrograma", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoProgramaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public findEstadoProgramaRequest() {
        }
        
        public findEstadoProgramaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findEstadoProgramaResponse", WrapperNamespace="http://ws.cem.pft8461.duoc.cl/", IsWrapped=true)]
    public partial class findEstadoProgramaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cem.pft8461.duoc.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public net.desktop.WebServiceEstadoPrograma.estadoPrograma @return;
        
        public findEstadoProgramaResponse() {
        }
        
        public findEstadoProgramaResponse(net.desktop.WebServiceEstadoPrograma.estadoPrograma @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadoProgramaWSChannel : net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoProgramaWSClient : System.ServiceModel.ClientBase<net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS>, net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EstadoProgramaWSClient() : 
                base(EstadoProgramaWSClient.GetDefaultBinding(), EstadoProgramaWSClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.EstadoProgramaWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoProgramaWSClient(EndpointConfiguration endpointConfiguration) : 
                base(EstadoProgramaWSClient.GetBindingForEndpoint(endpointConfiguration), EstadoProgramaWSClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoProgramaWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EstadoProgramaWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoProgramaWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EstadoProgramaWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadoProgramaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS.editEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.editEstadoPrograma request) {
            return base.Channel.editEstadoProgramaAsync(request);
        }
        
        public System.Threading.Tasks.Task editEstadoProgramaAsync(int id_estado, string estado) {
            net.desktop.WebServiceEstadoPrograma.editEstadoPrograma inValue = new net.desktop.WebServiceEstadoPrograma.editEstadoPrograma();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS)(this)).editEstadoProgramaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS.removeEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.removeEstadoPrograma request) {
            return base.Channel.removeEstadoProgramaAsync(request);
        }
        
        public System.Threading.Tasks.Task removeEstadoProgramaAsync(int entity) {
            net.desktop.WebServiceEstadoPrograma.removeEstadoPrograma inValue = new net.desktop.WebServiceEstadoPrograma.removeEstadoPrograma();
            inValue.entity = entity;
            return ((net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS)(this)).removeEstadoProgramaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS.createEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.createEstadoPrograma request) {
            return base.Channel.createEstadoProgramaAsync(request);
        }
        
        public System.Threading.Tasks.Task createEstadoProgramaAsync(int id_estado, string estado) {
            net.desktop.WebServiceEstadoPrograma.createEstadoPrograma inValue = new net.desktop.WebServiceEstadoPrograma.createEstadoPrograma();
            inValue.id_estado = id_estado;
            inValue.estado = estado;
            return ((net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS)(this)).createEstadoProgramaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findAllEstadoProgramaResponse> net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS.findAllEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.findAllEstadoProgramaRequest request) {
            return base.Channel.findAllEstadoProgramaAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findAllEstadoProgramaResponse> findAllEstadoProgramaAsync() {
            net.desktop.WebServiceEstadoPrograma.findAllEstadoProgramaRequest inValue = new net.desktop.WebServiceEstadoPrograma.findAllEstadoProgramaRequest();
            return ((net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS)(this)).findAllEstadoProgramaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findEstadoProgramaPorResponse> net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS.findEstadoProgramaPorAsync(net.desktop.WebServiceEstadoPrograma.findEstadoProgramaPorRequest request) {
            return base.Channel.findEstadoProgramaPorAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findEstadoProgramaPorResponse> findEstadoProgramaPorAsync(string campo, string valor) {
            net.desktop.WebServiceEstadoPrograma.findEstadoProgramaPorRequest inValue = new net.desktop.WebServiceEstadoPrograma.findEstadoProgramaPorRequest();
            inValue.campo = campo;
            inValue.valor = valor;
            return ((net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS)(this)).findEstadoProgramaPorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findEstadoProgramaResponse> net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS.findEstadoProgramaAsync(net.desktop.WebServiceEstadoPrograma.findEstadoProgramaRequest request) {
            return base.Channel.findEstadoProgramaAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.desktop.WebServiceEstadoPrograma.findEstadoProgramaResponse> findEstadoProgramaAsync(int id) {
            net.desktop.WebServiceEstadoPrograma.findEstadoProgramaRequest inValue = new net.desktop.WebServiceEstadoPrograma.findEstadoProgramaRequest();
            inValue.id = id;
            return ((net.desktop.WebServiceEstadoPrograma.EstadoProgramaWS)(this)).findEstadoProgramaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoProgramaWSPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EstadoProgramaWSPort)) {
                return new System.ServiceModel.EndpointAddress("http://ws.huevoscopita.cl/webservice/EstadoProgramaWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return EstadoProgramaWSClient.GetBindingForEndpoint(EndpointConfiguration.EstadoProgramaWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return EstadoProgramaWSClient.GetEndpointAddress(EndpointConfiguration.EstadoProgramaWSPort);
        }
        
        public enum EndpointConfiguration {
            
            EstadoProgramaWSPort,
        }
    }
}
